In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [5]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [6]:
# Create our features
x_df = df.drop(columns=['loan_status'])
X = pd.get_dummies(x_df, columns=['home_ownership', 'verification_status', 'issue_d',
       'pymnt_plan', 'initial_list_status', 'next_pymnt_d', 'application_type',
       'hardship_flag', 'debt_settlement_flag'])

# Create our target
y = df["loan_status"]

In [7]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [9]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y, random_state=1, stratify=y)
Counter(y_train)

Counter({'low_risk': 51352, 'high_risk': 260})

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [12]:
from sklearn.preprocessing import StandardScaler
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [13]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
rf_model = BalancedRandomForestClassifier(n_estimators=100, random_state=78) 
rf_model.fit(X_train_scaled, y_train)

BalancedRandomForestClassifier(random_state=78)

In [14]:
# Calculated the balanced accuracy score
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
y_pred = rf_model.predict(X_test_scaled)
accuracy_score(y_test, y_pred)

0.8981110142400465

In [15]:
# Display the confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(
    cm, index=["Actual High Risk", "Actual Low Risk"], columns=["Predicted High Risk", "Predicted Low Risk"])

cm_df

                  Predicted High Risk  Predicted Low Risk
Actual High Risk                   64                  23
Actual Low Risk                  1730               15388

In [16]:
# Print the imbalanced classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

   high_risk       0.04      0.74      0.07        87
    low_risk       1.00      0.90      0.95     17118

    accuracy                           0.90     17205
   macro avg       0.52      0.82      0.51     17205
weighted avg       0.99      0.90      0.94     17205

In [17]:
# List the features sorted in descending order by feature importance
importances = rf_model.feature_importances_
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.07362790213703933, 'last_pymnt_amnt'),
 (0.06853966344585831, 'total_rec_prncp'),
 (0.06175997356251755, 'total_pymnt_inv'),
 (0.05950215565140238, 'total_pymnt'),
 (0.04881622375770645, 'total_rec_int'),
 (0.02646781976760606, 'int_rate'),
 (0.017935474393771442, 'installment'),
 (0.01788125828785652, 'issue_d_Jan-2019'),
 (0.01774244892169198, 'mths_since_recent_inq'),
 (0.017025653382687123, 'out_prncp_inv'),
 (0.016982479861349983, 'dti'),
 (0.016727934013354227, 'annual_inc'),
 (0.01583481112610899, 'bc_util'),
 (0.01572871462427177, 'out_prncp'),
 (0.01571029742040408, 'revol_bal'),
 (0.015391899007445434, 'issue_d_Mar-2019'),
 (0.01535526912112122, 'tot_hi_cred_lim'),
 (0.015123376572214792, 'max_bal_bc'),
 (0.014794724586247456, 'il_util'),
 (0.014171008987148346, 'all_util'),
 (0.01401917878020906, 'mo_sin_old_rev_tl_op'),
 (0.014009516147055614, 'bc_open_to_buy'),
 (0.0139129523984448, 'total_bal_ex_mort'),
 (0.013892442171923775, 'mo_sin_old_il_acct'),
 (0.013844878802779176, 'total_rev_hi_lim'),
 (0.013587721891284854, 'mths_since_rcnt_il'),
 (0.013260973175448096, 'avg_cur_bal'),
 (0.01300800562278965, 'total_bal_il'),
 (0.012450117352192609, 'total_bc_limit'),
 (0.01237111022049006, 'total_il_high_credit_limit'),
 (0.012319064338314175, 'tot_cur_bal'),
 (0.011323552627356624, 'open_acc'),
 (0.010784983054441621, 'mo_sin_rcnt_tl'),
 (0.010643970851108861, 'mo_sin_rcnt_rev_tl_op'),
 (0.010439018270011176, 'num_rev_accts'),
 (0.010429927947218809, 'mths_since_recent_bc'),
 (0.009929113504110252, 'total_acc'),
 (0.009442173588305043, 'num_rev_tl_bal_gt_0'),
 (0.009438465757486341, 'loan_amnt'),
 (0.00921444377050424, 'total_cu_tl'),
 (0.009183210718369847, 'num_bc_sats'),
 (0.008991479599080966, 'num_sats'),
 (0.008833275619577165, 'num_op_rev_tl'),
 (0.008552631969314179, 'num_actv_bc_tl'),
 (0.008262315970679938, 'open_rv_24m'),
 (0.008251352950894209, 'inq_last_12m'),
 (0.008118768845928315, 'num_actv_rev_tl'),
 (0.008033279769211256, 'pct_tl_nvr_dlq'),
 (0.007593894758127955, 'delinq_2yrs'),
 (0.007284646865376094, 'percent_bc_gt_75'),
 (0.007275681692348642, 'acc_open_past_24mths'),
 (0.007166282321090392, 'num_il_tl'),
 (0.007159677604791848, 'num_tl_op_past_12m'),
 (0.007013077937954682, 'num_bc_tl'),
 (0.006843973884241612, 'inq_fi'),
 (0.006840915311474935, 'open_il_24m'),
 (0.006763298800323072, 'mort_acc'),
 (0.0065044758401964905, 'total_rec_late_fee'),
 (0.004711957035498209, 'next_pymnt_d_Apr-2019'),
 (0.004659177420864069, 'inq_last_6mths'),
 (0.00459318181089356, 'open_acc_6m'),
 (0.004576660448885694, 'open_act_il'),
 (0.004349828942845732, 'issue_d_Feb-2019'),
 (0.0038244647272339984, 'tot_coll_amt'),
 (0.0031984723089791833, 'open_rv_12m'),
 (0.003136470296376004, 'open_il_12m'),
 (0.0028689968969480856, 'next_pymnt_d_May-2019'),
 (0.0023483145693438566, 'num_accts_ever_120_pd'),
 (0.0022207102237771863, 'verification_status_Verified'),
 (0.0020090714991068733, 'verification_status_Not Verified'),
 (0.0019626623573582897, 'home_ownership_OWN'),
 (0.0018696237911081984, 'home_ownership_MORTGAGE'),
 (0.001643835814723478, 'verification_status_Source Verified'),
 (0.0016104620527846556, 'pub_rec_bankruptcies'),
 (0.0014440744477385104, 'home_ownership_RENT'),
 (0.0012152820426930247, 'num_tl_90g_dpd_24m'),
 (0.0011909840815334226, 'application_type_Joint App'),
 (0.0011552689465138223, 'pub_rec'),
 (0.001155071266298661, 'initial_list_status_f'),
 (0.001102003576273648, 'application_type_Individual'),
 (0.0005946796624498203, 'initial_list_status_w'),
 (0.00022076846610374144, 'chargeoff_within_12_mths'),
 (0.00017210676947228919, 'collections_12_mths_ex_med'),
 (5.293118593611211e-05, 'home_ownership_ANY'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [18]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
rf_model1 = EasyEnsembleClassifier(n_estimators=100, random_state=78) 
rf_model1.fit(X_train_scaled, y_train)

EasyEnsembleClassifier(n_estimators=100, random_state=78)

In [19]:
# Calculated the balanced accuracy score
y_pred1 = rf_model1.predict(X_test_scaled)
accuracy_score(y_test, y_pred1)

0.9468759081662308

In [20]:
# Display the confusion matrix
cm1 = confusion_matrix(y_test, y_pred1)
cm_df1 = pd.DataFrame(
    cm1, index=["Actual High Risk", "Actual Low Risk"], columns=["Predicted High Risk", "Predicted Low Risk"])

cm_df1

                  Predicted High Risk  Predicted Low Risk
Actual High Risk                   79                   8
Actual Low Risk                   906               16212

In [21]:
# Print the imbalanced classification report
print(classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

   high_risk       0.08      0.91      0.15        87
    low_risk       1.00      0.95      0.97     17118

    accuracy                           0.95     17205
   macro avg       0.54      0.93      0.56     17205
weighted avg       0.99      0.95      0.97     17205